name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.0.0-chrome-124.0.6367.60-1-ff-125.0.2-edge-124.0.2478.51-1
      options: --user 1001
    steps:
    - name: Pegar Codigo
      uses:  actions/checkout@v4.2.2

    - name: Instalar dependencias
      run: yarn install

    - name: Rodar testes E2E
      run: node runner-electron.js
    env:
      TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_ELECTRON }}
      
  cypress-chrome-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.0.0-chrome-124.0.6367.60-1-ff-125.0.2-edge-124.0.2478.51-1
      options: --user 1001
    steps:
    - name: Pegar Codigo
      uses:  actions/checkout@v4.2.2

    - name: Instalar dependencias
      run: yarn install

    - name: Rodar testes E2E
      run: node runner-chrome.js
    env:
      TARGET_TOKEN_CHROME: ${{ secrets.TARGET_TOKEN_CHROME }}  

  cypress-firefox-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.0.0-chrome-124.0.6367.60-1-ff-125.0.2-edge-124.0.2478.51-1
      options: --user 1001
    steps:
    - name: Pegar Codigo
      uses:  actions/checkout@v4.2.2

    - name: Instalar dependencias
      run: yarn install

    - name: Rodar testes E2E
      run: node runner-firefox.js
    env:
      TARGET_TOKEN_FIREFOX: ${{ secrets.TARGET_TOKEN_FIREFOX }}    
