name: Cypress Tests

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Pegar Codigo
      uses:  actions/checkout@v4.2.2

    - name: Instalar dependencias
      run: yarn install

    - name: Rodar testes E2E
      run: yarn cypress run
