name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress node command 
        default: node runner.js

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.0.0-chrome-124.0.6367.60-1-ff-125.0.2-edge-124.0.2478.51-1
      options: --user 1001
    steps:
    - name: Pegar Codigo
      uses:  actions/checkout@v4.2.2

    - name: Instalar dependencias
      run: yarn install

    - name: Rodar testes E2E
      run: ${{ github.event.inputs.cli }}
